name: galaxy_store
description: A new Flutter project.
 
publish_to: 'none'
 
version: 2.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.1+4 
  http: ^0.12.0+2
  password_hash: 2.0.0
  imei_plugin: 1.1.6
  encrypt: 3.3.1 
  percent_indicator: 2.1.1+1
  barcode_scan: 1.0.0
  splashscreen: ^1.2.0
  vibration: 1.2.1
  flutter_launcher_icons: "^0.7.3" 
  audioplayers: 0.13.2
  progress_dialog: 1.2.0
  flutter_markdown: 0.3.4
  connectivity: 0.4.8+6
  flushbar: 1.10.4 
  flutter_datetime_picker: 1.4.0 
  convex_bottom_bar: 3.0.0
  group_radio_button: 1.0.1
  searchable_dropdown: 1.1.2
  date_field: 0.3.3 
  intl: ^0.16.1
  hand_signature: 0.6.3
  path_provider: 1.6.27
  dio: 3.0.10
  table_sticky_headers: 1.2.0  
  back_button_interceptor: 4.4.1
  dropdown_search: 0.5.0
  flutter_cache_manager: ^1.1.3
  date_format: 2.0.2
  shared_preferences: 0.5.12+4
  awesome_dialog: 
  package_info: ^0.4.0+16
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "/assets/img/app-icon.png"
  
flutter:
  assets:
      - assets/sounds/
      - assets/img/loading-1.gif
      - assets/img/loading-2.gif
      - assets/img/app-icon.png
  uses-material-design: true
 